#!/bin/bash
set -e

userConfPath="/etc/sftp-users.conf"
userConfFinalPath="/var/run/sftp-users.conf"

# modify php-fpm conf
sed -i -r 's#(error_log) =.*#\1 = /dev/stdout#' /etc/php5/fpm/php-fpm.conf

function printHelp() {
    echo "Add users as command arguments, STDIN or mounted in $userConfPath"
    echo "Syntax: user:pass[:e][:uid[:gid]]..."
    echo "Use --readme for more information and examples."
}

function printReadme() {
    cat /README.md
    echo "TIP: Read this in HTML format here: https://github.com/atmoz/sftp"
}

function createUser() {
    IFS=':' read -a param <<< $@
    user="${param[0]}"
    pass="${param[1]}"

    if [ "${param[2]}" == "e" ]; then
        chpasswdOptions="-e"
        uid="${param[3]}"
        gid="${param[4]}"
    else
        uid="${param[2]}"
        gid="${param[3]}"
    fi

    if [ -z "$user" ]; then
        echo "FATAL: You must at least provide a username."
        exit 1
    fi

    if $(cat /etc/passwd | cut -d: -f1 | grep -q "$user"); then
        echo "FATAL: User \"$user\" already exists."
        exit 2
    fi

    useraddOptions="--no-user-group --system --home-dir=/mnt"

    if [ -n "$uid" ]; then
        useraddOptions="$useraddOptions --non-unique --uid $uid"
    fi

    if [ -n "$gid" ]; then
        if ! $(cat /etc/group | cut -d: -f3 | grep -q "$gid"); then
            groupadd --gid $gid $gid
        fi

        useraddOptions="$useraddOptions --gid $gid"
    fi

    useradd $useraddOptions $user
    chown root:root /mnt
    chmod 755 /mnt

    if [ -z "$pass" ]; then
        pass="$(echo `</dev/urandom tr -dc A-Za-z0-9 | head -c256`)"
        chpasswdOptions=""
    fi

    echo "$user:$pass" | chpasswd $chpasswdOptions

    # Add SSH keys to authorized_keys with valid permissions
    if [ -d /data/.ssh/keys ]; then
        cat /data/.ssh/keys/* >> /data/.ssh/authorized_keys
        chown $user /data/.ssh/authorized_keys
        chmod 600 /data/.ssh/authorized_keys
    fi
}


# Create users only on first run
if [ ! -f "$userConfFinalPath" ]; then

    # Append mounted config to final config
    if [ -f "$userConfPath" ]; then
        cat "$userConfPath" > "$userConfFinalPath"
    fi

    # Append users from arguments to final config
    if [ $SFTP_USER ] && [ $SFTP_PASS ];then
        echo "$SFTP_USER:$SFTP_PASS:200:200" >> "$userConfFinalPath"
    else
        for user in "$@"; do
            echo "$user" >> "$userConfFinalPath"
        done
    fi
    
    # Append users from STDIN to final config
    if [ ! -t 0 ]; then
        while IFS= read -r user || [[ -n "$user" ]]; do
            echo "$user" >> "$userConfFinalPath"
        done
    fi

    # Check that we have users in config
    if [ "$(cat "$userConfFinalPath" | wc -l)" == 0 ]; then
        echo "FATAL: No users provided!"
        printHelp
        exit 3
    fi

    # Import users from final conf file
    while IFS= read -r user || [[ -n "$user" ]]; do
        createUser "$user"
    done < "$userConfFinalPath"

    # Source custom scripts, if any
    if [ -d /etc/sftp.d ]; then
        for f in /etc/sftp.d/*; do
            [ -x "$f" ] && . "$f"
        done
        unset f
    fi
fi

echo "==========================================================="
echo 
echo "Please use the User : [ $SFTP_USER ], Password: [ $SFTP_PASS ] connection sftp service. "
echo 
echo "==========================================================="

# run php5-fpm
/usr/sbin/php5-fpm --daemonize

# run sshd
exec /usr/sbin/sshd

# run nginx
/usr/sbin/nginx
